# /*********************************************************************
# *
# *  Software License Agreement
# *
# *  Copyright (c) 2023,
# *  TU Dortmund University, Institute of Control Theory and System Engineering
# *  All rights reserved.
# *
# *  This program is free software: you can redistribute it and/or modify
# *  it under the terms of the GNU General Public License as published by
# *  the Free Software Foundation, either version 3 of the License, or
# *  (at your option) any later version.
# *
# *  This program is distributed in the hope that it will be useful,
# *  but WITHOUT ANY WARRANTY; without even the implied warranty of
# *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# *  GNU General Public License for more details.
# *
# *  You should have received a copy of the GNU General Public License
# *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# *
# *  Authors: Maximilian Krämer
# *  Maintainer(s)/Modifier(s): Heiko Renz
# *********************************************************************/

dynamic_obstacles:
  - id: 1
    group_id: 1
    name: Cylinder
    length_x: 0.5
    radius: 0.1
    translation: [2.0, 1.0, 0.9]
    rotation: [0.0, -1.57, 0.0]
  - id: 2
    group_id: 2
    name: Sphere
    length_x: 0.0
    radius: 0.1
    translation: [2.0, -1.0, 0.9]
    rotation: [0.0, 0.0, 0.0]
  - id: 3
    group_id: 3
    name: Box
    length_x: 0.2
    length_y: 0.1
    radius: 0.05
    translation: [1.8, 0.0, 0.9]
    rotation: [0.0, 0.0, 0.0]
  - id: 4
    group_id: 4
    name: EBox
    length_x: 0.2
    length_y: 0.1
    extruded: true
    translation: [1.0, -1.0, 0.9]
    rotation: [0.0, 0.0, 0.0]
