# /*********************************************************************
# *
# *  Software License Agreement
# *
# *  Copyright (c) 2023,
# *  TU Dortmund University, Institute of Control Theory and System Engineering
# *  All rights reserved.
# *
# *  This program is free software: you can redistribute it and/or modify
# *  it under the terms of the GNU General Public License as published by
# *  the Free Software Foundation, either version 3 of the License, or
# *  (at your option) any later version.
# *
# *  This program is distributed in the hope that it will be useful,
# *  but WITHOUT ANY WARRANTY; without even the implied warranty of
# *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# *  GNU General Public License for more details.
# *
# *  You should have received a copy of the GNU General Public License
# *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# *
# *  Authors: Maximilian Krämer
# *  Maintainer(s)/Modifier(s): Heiko Renz
# *********************************************************************/

static_obstacles:
  - id: 1 # H
    group_id: 1 #Wall
    name: Cylinder
    length: 1.79
    radius: 0.1
    translation: [0.74, 0.11, 0.0]
    rotation: [0.0, -1.57, 0.0]
  - id: 2 # M
    group_id: 1
    name: Cylinder
    length: 1.79
    radius: 0.1
    translation: [0.94, 0.11, 0.0]
    rotation: [0.0, -1.57, 0.0]
  - id: 3 # V
    group_id: 1
    name: Cylinder
    length: 1.79
    radius: 0.1
    translation: [1.14, 0.11, 0.0]
    rotation: [0.0, -1.57, 0.0]
