image: docker:git
services:
  - docker:dind
before_script:
  #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.rst.e-technik.tu-dortmund.de:5005
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD git.rst.e-technik.tu-dortmund.de:5005

stages:
  - base

mhp:
  stage: base
  script:
    - docker build -t git.rst.e-technik.tu-dortmund.de:5005/robotics-rigid-arms/mhp:melodic_devel docker

  tags:
    - ubuntu
    - docker
