<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ur_description)/urdf/ur.transmission.xacro" />



  <!-- Inertia parameters -->
  <xacro:property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
  <xacro:property name="shoulder_mass" value="7.778" />
  <xacro:property name="upper_arm_mass" value="12.93" />
  <xacro:property name="forearm_mass" value="3.87" />
  <xacro:property name="wrist_1_mass" value="1.96" />
  <xacro:property name="wrist_2_mass" value="1.96" />
  <xacro:property name="wrist_3_mass" value="0.202" />

  <!-- These parameters are borrowed from the urcontrol.conf file
       but are not verified for the correct permutation.
       The permutation was guessed by looking at the UR5 parameters.
       Serious use of these parameters needs further inspection. -->
  <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
  <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
  <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
  <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
  <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
  <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <xacro:property name="ur10_d1" value="0.1273" />
  <xacro:property name="ur10_a2" value="-0.612" />
  <xacro:property name="ur10_a3" value="-0.5723" />
  <xacro:property name="ur10_d4" value="0.163941" />
  <xacro:property name="ur10_d5" value="0.1157" />
  <xacro:property name="ur10_d6" value="0.0922" />

  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <xacro:property name="shoulder_offset" value="0.220941" />  <!-- measured from model -->
  <xacro:property name="elbow_offset" value="-0.1719" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <xacro:property name="shoulder_height" value="${ur10_d1}" />
  <xacro:property name="upper_arm_length" value="${-ur10_a2}" />
  <xacro:property name="forearm_length" value="${-ur10_a3}" />
  <xacro:property name="wrist_1_length" value="${ur10_d4 - elbow_offset - shoulder_offset}" />
  <xacro:property name="wrist_2_length" value="${ur10_d5}" />
  <xacro:property name="wrist_3_length" value="${ur10_d6}" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="ur10_robot" params="prefix joint_limited shoulder_pan_lower_limit shoulder_pan_upper_limit
                                         shoulder_lift_lower_limit shoulder_lift_upper_limit elbow_joint_lower_limit
                                         elbow_joint_upper_limit wrist_1_lower_limit wrist_1_upper_limit 
                                         wrist_2_lower_limit wrist_2_upper_limit wrist_3_lower_limit wrist_3_upper_limit">

    <link name="${prefix}base_link" >
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/base.dae"/>
        </geometry>
      </visual>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/shoulder.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.0"/>
        <geometry>
          <sphere radius="0.11"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link = "${prefix}upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/upperarm.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 -0.05 0.3"/>
        <geometry>
          <cylinder length="0.6" radius="0.11"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 -0.05 0"/>
        <geometry>
          <sphere radius="0.11"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 -0.05 0.6"/>
        <geometry>          
          <sphere radius="0.11"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link = "${prefix}forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/forearm.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.28"/>
        <geometry>	  
          <cylinder length="0.56" radius="0.08"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.56"/>
        <geometry>
          <sphere radius="0.08"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <sphere radius="0.08"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link = "${prefix}wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/wrist1.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0.1149 0"/>
        <geometry>
          <sphere radius="0.07"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link = "${prefix}wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/wrist2.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="-${pi/2} 0 0" xyz="0 0.0 0.1157"/>
        <geometry>
          <cylinder length="0.08" radius="0.05"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 -0.04 0.1157"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 0.04 0.1157"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/wrist3.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0.1 0"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}ee_fixed_joint" type="fixed">
      <parent link="${prefix}wrist_3_link" />
      <child link = "${prefix}ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${prefix}ee_link" />

    <xacro:ur_arm_transmission prefix="${prefix}" />

    <link name="pedestal_link">
      <visual>
        <origin rpy="0.0 0.0 0.0" xyz="-0.23 -0.33 -0.013"/>
        <geometry>
          <mesh filename="package://ur_description/meshes/rst_ft/rst_base.stl" scale="0.0255 0.0255 0.0253" />
        </geometry>
        <material name="darkgray"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.38"/>
        <geometry>
          <cylinder radius="0.1" length="0.76"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.76"/>
        <geometry>
          <sphere radius="0.1"/>
        </geometry>
      </collision>
    </link>

    <joint name="mount" type="fixed">
      <origin rpy="0 0 0" xyz="0.0 0.0 0.8"/>
      <parent link="pedestal_link"/>
      <child link="base_link"/>
    </joint>

    <link name="world"/>
    <link name="ground"/>
    <link name="roof"/>

    <joint name="world_joint" type="fixed">
      <parent link="world"/>
      <child link="pedestal_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
    </joint>

    <joint name="ground_joint" type="fixed">
      <parent link="world"/>
      <child link="ground"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
    </joint>

    <joint name="roof_joint" type="fixed">
      <parent link="world"/>
      <child link="roof"/>
      <origin rpy="3.14 0.0 0.0" xyz="0.0 0.0 2.5"/>
    </joint>

    <gazebo reference="pedestal_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="base_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="shoulder_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="upper_arm_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="forearm_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="wrist_1_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="wrist_2_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="wrist_3_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

    <gazebo reference="ee_link">
      <turnGravityOff>1</turnGravityOff>
    </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/ur10</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

  </xacro:macro>
</robot>
