
#  *  Software License Agreement
#  *
#  *  Copyright (c) 2023,
#  *  TU Dortmund University, Institute of Control Theory and System Enginnering
#  *  All rights reserved.
#  *
#  *  This program is free software: you can redistribute it and/or modify
#  *  it under the terms of the GNU General Public License as published by
#  *  the Free Software Foundation, either version 3 of the License, or
#  *  (at your option) any later version.
#  *
#  *  This program is distributed in the hope that it will be useful,
#  *  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  *  GNU General Public License for more details.
#  *
#  *  You should have received a copy of the GNU General Public License
#  *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#  *
#  *  Authors: Heiko Renz

# The default task is deined for the UR10 example
task:
  task_type: URTask
  initial_goal_state: [1.0, -0.3, 0.0, 0.0, 0.0, 0.0]
  
  sim_time: 1000
  dt: 0.1

  computation_delay: 0.0
  computation_delay_filter:
    filter_type: None # None, MovingAverageFilter, MovingMedianFilter, MovingLeastSquaresFilter
    moving_average: 
      window_size: 5
    moving_median:
      window_size: 5
    moving_least_squares:
      window_size: 5
      polynomial_order: 3
  general_offset_delay: 0.0